[package]
name = "classroom-deck"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Magnus Simonsen"]
license = "MIT"
description = "Clean classroom slides with pause animations."
homepage = "https://github.com/magnussimonsen/highschool_slides"
repository = "https://github.com/magnussimonsen/highschool_slides"
keywords = ["presentation", "slides", "template", "animation"]
categories = ["presentation"]
disciplines = ["education"]
compiler = "0.12.0"

[package.exclude]
["*.pdf", "test_*.typ"]
